//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrecios.Models.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comercio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comercio()
        {
            this.ListaArticuloes = new HashSet<ListaArticulo>();
            this.Precios = new HashSet<Precio>();
        }
    
        public int C_id { get; set; }
        public string id { get; set; }
        public Nullable<int> comercio_id { get; set; }
        public string comercio_razon_social { get; set; }
        public Nullable<int> bandera_id { get; set; }
        public string bandera_descripcion { get; set; }
        public string sucursal_tipo { get; set; }
        public string sucursal_nombre { get; set; }
        public string provincia { get; set; }
        public string localidad { get; set; }
        public string direccion { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaArticulo> ListaArticuloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio> Precios { get; set; }
    }
}
