//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrecios.Models.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPrecios : DbContext
    {
        public DBPrecios()
            : base("name=DBPreciosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Comercio> Comercios { get; set; }
        public virtual DbSet<ListaArticulo> ListaArticuloes { get; set; }
        public virtual DbSet<Lista> Listas { get; set; }
        public virtual DbSet<Precio> Precios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
