//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrecios.Models.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaArticulo
    {
        public int idLista { get; set; }
        public string idArticulo { get; set; }
        public Nullable<decimal> precioOptimo { get; set; }
        public Nullable<decimal> precioReal { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string idComercio { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Comercio Comercio { get; set; }
        public virtual Lista Lista { get; set; }
    }
}
