//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrecios.Models.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int C_id { get; set; }
        public string id_comercio { get; set; }
        public string id_articulo { get; set; }
        public Nullable<decimal> precio1 { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Comercio Comercio { get; set; }
    }
}
